import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {movimentar,totais,posicaoEm,alertaObra,diaSP} from './app-sao-gabriel/estoque-core.js';
const data=diaSP();
let locais=[{id:'u',tipo:'usina',nome:'Usina',saldo:0,ativo:true,inicializado:false,ultima:''},{id:'v',tipo:'veiculo',nome:'ABC1D23',saldo:0,ativo:true,inicializado:false,ultima:''},{id:'o',tipo:'obra',nome:'Obra',empresa:'e',saldo:0,ativo:true,inicializado:false,ultima:''}];
const log=[];
function move(tipo,quantidade,origem='',destino='',motivo='Teste'){const result=movimentar(locais,{tipo,quantidade,origem,destino,motivo,data});locais=result.locais;log.push(result.movimento);return result.movimento;}
move('inicial',20,'','u');assert.equal(totais(locais).total,20);
assert.throws(()=>move('inicial',20,'','u'),/já possui/);
move('carregamento',5,'u','v');move('entrega',3,'v','o');assert.deepEqual(totais(locais),{obra:3,veiculo:2,usina:15,total:20});
const troca=move('troca',1,'v','o');assert.equal(locais.find(l=>l.id==='o').saldo,3);assert.equal(totais(locais).total,20);
assert.throws(()=>move('entrega',3,'v','o'),/suficientes/);assert.throws(()=>move('entrega',1,'u','o'),/incompatíveis/);
assert.throws(()=>move('baixa',1,'','u',''),/motivo/);assert.throws(()=>move('entrada',1.5,'','u'),/inteira/);
move('retirada',1,'o','v');move('descarregamento',2,'v','u');assert.equal(totais(locais).total,20);
const entrada=move('entrada',4,'','u');assert.equal(totais(locais).total,24);
const reversed=movimentar(locais,{tipo:'estorno',data,motivo:'Duplicado'},entrada);locais=reversed.locais;log.push(reversed.movimento);assert.equal(totais(locais).total,20);
assert.throws(()=>movimentar(locais,{tipo:'estorno',data,motivo:'Duplicado'},{...entrada,estornadoPor:'x'}),/não pode/);
move('ajuste',10,'','u');assert.equal(locais.find(l=>l.id==='u').saldo,10);
move('baixa',1,'','u');assert.equal(locais.find(l=>l.id==='u').saldo,9);
assert.throws(()=>move('baixa',100,'','u'),/negativo/);
assert.throws(()=>movimentar(locais,{tipo:'ajuste',quantidade:2,destino:'o',data:'2026-02-31',motivo:'Erro'}),/válida/);
assert.throws(()=>movimentar(locais,{tipo:'ajuste',quantidade:2,destino:'o',data:'2020-01-01',motivo:'Erro'}),/última/);
const saldos=posicaoEm(log,data);for(const l of locais)assert.equal(saldos[l.id],l.saldo);
assert.deepEqual(posicaoEm(log,'2000-01-01'),{});
const obra=locais.find(l=>l.id==='o');assert.match(alertaObra(obra,[]),/Sem autorização vinculada/);
assert.equal(alertaObra(obra,[{obraId:'o',autorizada:true,qtd:10,inicio:data,fim:data}],data),'');
assert.match(alertaObra(obra,[{obraId:'o',autorizada:true,qtd:1,inicio:data,fim:data}],data),/acima/);
const html=fs.readFileSync('app-sao-gabriel/index.html','utf8');new vm.Script(html.match(/<script type="module">([\s\S]*?)<\/script>/)[1].replace(/^import .*$/gm,''));
console.log('OK: saldos iniciais, 4 transferências, troca, ajuste, entrada/baixa, estorno, saldo negativo, datas, histórico e alertas por obra.');
