const fs=require('fs'),assert=require('assert');
const {chromium}=require('C:/Users/LOGISTICA/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://app.test/**',r=>r.fulfill({contentType:'text/html',body:'<div id="app"></div>'}));await page.goto('https://app.test/');await page.addStyleTag({content:fs.readFileSync('app-sao-gabriel/style.css','utf8')});
await page.addScriptTag({content:`const montarImportacao=()=>{};const diaSP=()=>'2026-10-06',serverTimestamp=()=>null;const auth={currentUser:{uid:'admin',email:'kewen.allan.nave@gmail.com'}},empresas=[{id:'a',nome:'Construtora Alfa',qtdCaixas:3,endereco:'Rua A',ultimaTrocaCaixas:'2026-10-01'},{id:'b',nome:'Empresa Beta',obrasCaixas:[{id:'b1',nome:'Edifício Sol',endereco:'Rua B',qtdCaixas:2,ultimaTrocaCaixas:'2026-09-01'},{id:'b2',nome:'Residencial Lua',endereco:'Rua C',qtdCaixas:4,ultimaTrocaCaixas:'2026-10-05'},{id:'b0',nome:'Sem caixas',endereco:'',qtdCaixas:0}]}];const doc=(db,c,id)=>({c,id}),onSnapshot=(r,fn)=>fn({exists:()=>false}),runTransaction=async(db,fn)=>fn({get:async r=>({exists:()=>true,data:()=>structuredClone(empresas.find(e=>e.id===r.id))}),update:(r,changes)=>Object.assign(empresas.find(e=>e.id===r.id),changes)});`});
await page.addScriptTag({content:fs.readFileSync('app-sao-gabriel/estoque-simples.js','utf8').replace(/^import .*$/gm,'').replace('export function','function')+';window.controle=iniciarEstoque({},auth,()=>({empresas}));controle.mostrar(true);'});
assert.deepEqual(await page.locator('.empresa-caixas-grupo>h3').allTextContents(),['CONSTRUTORA ALFA','EMPRESA BETA']);assert.equal(await page.locator('[data-obra]').count(),3);assert.equal(await page.locator('.estoque-stats b').first().textContent(),'9');
await page.locator('#caixas-busca').fill('Beta');assert.equal(await page.locator('[data-obra]').count(),2);await page.locator('#caixas-busca').fill('Lua');assert.equal(await page.locator('[data-obra]').count(),1);await page.locator('#caixas-busca').fill('');await page.locator('#caixas-ordem').selectOption('tempo');assert.equal(await page.locator('.empresa-caixas-grupo>h3').first().textContent(),'EMPRESA BETA');assert.equal(await page.locator('[data-obra]').first().getAttribute('data-obra'),'b1');
await page.locator('[data-cliente="a"]').click();await page.locator('#obra-nome').fill('Obra Centro');await page.locator('#caixas-entrega').fill('2026-10-06');await page.getByRole('button',{name:'Salvar obra',exact:true}).click();assert.equal(await page.evaluate(()=>empresas[0].obrasCaixas[0].qtdCaixas),3);assert.equal(await page.evaluate(()=>empresas[0].obrasCaixas[0].dataEntregaDevolucao),'2026-10-06');assert.equal(await page.locator('.estoque-stats b').first().textContent(),'9');
await page.locator('summary').click();await page.locator('#caixas-incluir').selectOption('a');await page.getByRole('button',{name:'+ Nova obra',exact:true}).click();await page.locator('#obra-nome').fill('Obra Norte');await page.locator('#caixas-qtd').fill('5');await page.getByRole('button',{name:'Salvar obra',exact:true}).click();assert.equal(await page.evaluate(()=>empresas[0].obrasCaixas.length),2);assert.equal(await page.locator('.estoque-stats b').first().textContent(),'14');
await page.evaluate(()=>{auth.currentUser=null;controle.mostrar(true);});assert.equal(await page.locator('#caixas-incluir').count(),0);assert.equal(await page.locator('[data-obra]').count(),0);assert.equal(await page.locator('.cliente-caixas').count(),4);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);await page.screenshot({path:'controle-obras-mobile.png',fullPage:true});
console.log('OK: empresas/obras, busca pelos dois nomes, ordem por troca, migração conserva saldo, nova obra, total sem duplicação, leitura pública e mobile.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
