const fs=require('fs'),assert=require('assert');
const {chromium}=require('C:/Users/LOGISTICA/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.setContent('<div id="app"></div>');await page.addStyleTag({content:fs.readFileSync('app-sao-gabriel/style.css','utf8')});
await page.addScriptTag({content:`const diaSP=()=>'2026-10-06',serverTimestamp=()=>({toDate:()=>new Date('2026-10-06T18:30:00Z')});const auth={currentUser:{uid:'admin',email:'kewen.allan.nave@gmail.com'}},empresas=[{id:'a',nome:'Cliente',qtdCaixas:5}];let data={estoque:{locais:[{id:'u',tipo:'usina',saldo:3},{id:'v',tipo:'veiculo',nome:'ABC',saldo:2}]}},listeners={};const doc=(db,c)=>c,snapshot=c=>({exists:()=>!!data[c],data:()=>data[c]}),onSnapshot=(c,fn)=>{listeners[c]=fn;fn(snapshot(c));},runTransaction=async(db,fn)=>fn({get:async c=>snapshot(c),set:(c,v)=>{data[c]=v;listeners[c](snapshot(c));}});`});
await page.addScriptTag({content:fs.readFileSync('app-sao-gabriel/estoque-simples.js','utf8').replace(/^import .*$/gm,'').replace('export function','function')+';window.controle=iniciarEstoque({},auth,()=>({empresas}));controle.mostrar(true);'});
assert.deepEqual(await page.locator('.estoque-stats b').allTextContents(),['5','2','3','10']);assert((await page.locator('#caixas-conferencia').textContent()).includes('Ainda não confirmada'));
await page.locator('[data-caixas-tela="usina"]').click();await page.locator('#usina-qtd').fill('8');assert(await page.locator('#caixas-confirmar').isDisabled());await page.getByRole('button',{name:'Salvar quantidade'}).click();assert.deepEqual(await page.locator('.estoque-stats b').allTextContents(),['5','2','8','15']);assert((await page.locator('#caixas-conferencia').textContent()).includes('Ainda não confirmada'));
await page.locator('#caixas-confirmar').click();assert((await page.locator('#caixas-conferencia').textContent()).includes('06/10/2026'));assert((await page.locator('#caixas-conferencia').textContent()).includes('15:30'));
await page.locator('#usina-qtd').fill('0');await page.getByRole('button',{name:'Salvar quantidade'}).click();assert.deepEqual(await page.locator('.estoque-stats b').allTextContents(),['5','2','0','7']);assert((await page.locator('#caixas-conferencia').textContent()).includes('15:30'));
await page.evaluate(()=>{auth.currentUser=null;controle.mostrar(true);});assert.equal(await page.locator('#usina-form').count(),0);assert.equal(await page.locator('#caixas-confirmar').count(),0);assert((await page.locator('#caixas-conferencia').textContent()).includes('15:30'));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);
console.log('OK: saldo da usina, totais sem duplicar, confirmação explícita, horário Brasília, zero, permissão visual e mobile.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
